Data Preprocessing

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
## Load the data
data = pd.read_csv('2.csv', sep=';', header=0)
data

,ENROLLMENT,TUITION PAYMENT MARCH 2022,TUITION PAYMENT MARCH 2023,GENDER,TYPE OF EDUCATIONAL INSTITUTION,EDUCATIONAL INSTITUTION,INSTITUTION STATUS,DEPARTMENT,PROVINCE,DISTRICT,...,CAMPUS,FACULTY,PROGRAM/MAJOR,SHIFT/SCHEDULE,BENEFIT DISCOUNTS,STUDY MODE,AGE RANGE OF ENROLLED STUDENT,DISABILITY,NUMBER OF ENROLLED COURSES,AT-RISK COURSE
0,Nuevo,0,0,M,INSTITUTO,IDAT,PRIVADA,LIMA,LIMA,BRENA,...,UTP Lima Centro,Fac. Ing. Sist. Y Elect.,ING. DE REDES Y COMUNICACIONES,MIXTO,SIN BENEFICIO,Presencial,5. >=30,No,0,0
1,Nuevo,1,0,M,COLEGIO,COLEGIO SISE,PRIVADA,LIMA,LIMA,VILLA MARIA DEL TRIUNFO,...,UTP Lima Centro,Fac. Ing. Sist. Y Elect.,ING. DE SISTEMAS,NOCHE,SIN BENEFICIO,Presencial,4. 24-29,No,3,0
2,Nuevo,1,1,F,NaN,NaN,NaN,LIMA,LIMA,JESUS MARIA,...,UTP Lima Centro,Fac. Der. Cienc. Polit. Y RRII,DERECHO,NOCHE,SIN BENEFICIO,Presencial,4. 24-29,No,1,0
3,Nuevo,0,0,F,COLEGIO,1220 SAN JOSE MARELLO,ESTATAL,LIMA,LIMA,ATE,...,UTP Lima Centro,Fac. Adm. Y Neg.,ADMINISTRACION DE NEGOCIOS (50/50),NOCHE,SIN BENEFICIO,Presencial,4. 24-29,No,0,0
4,Nuevo,1,1,F,INSTITUTO,IDAT,PRIVADA,LIMA,LIMA,SURQUILLO,...,UTP Lima Centro,Fac. Adm. Y Neg.,ADM. DE NEGOCIOS INTERNACIO,MAÑANA,CONVENIOS,Presencial,4. 24-29,No,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37577,Reinscrito,1,1,F,NaN,UNIVERSIDAD,NaN,AREQUIPA,AREQUIPA,CAYMA,...,UTP Virtual,Fac. Hum y CC Soc,PSICOLOGIA (VIRTUAL),MIXTO,SIN BENEFICIO,Virtual,5. >=30,No,2,0
37578,Reinscrito,1,1,F,NaN,NaN,NaN,LIMA,LIMA,LURIGANCHO,...,UTP Virtual,Fac. Hum y CC Soc,PSICOLOGIA (VIRTUAL),MIXTO,SIN BENEFICIO,Virtual,5. >=30,No,3,0
37579,Reinscrito,1,1,F,NaN,NaN,NaN,LIMA,LIMA,LIMA,...,UTP Virtual,Fac. Adm. Y Neg.,ADM. DE EMPRESAS (VIRTUAL),NOCHE,SIN BENEFICIO,Virtual,5. >=30,No,3,0
37580,Reinscrito,1,1,M,UNIVERSIDAD,PONTIFICIAUNIVERSIDADCATÓLIC,PRIVADA,LIMA,LIMA,CHORRILLOS,...,UTP Virtual,Fac. Ing. Ind. Y Mec.,ING. INDUSTRIAL (VIRTUAL),MIXTO,SIN BENEFICIO,Virtual,5. >=30,No,3,0
37581,Reinscrito,1,1,F,NaN,NaN,NaN,LIMA,LIMA,COMAS,...,UTP Virtual,Fac. Der. Cienc. Polit. Y RRII,DERECHO (VIRTUAL),MIXTO,SIN BENEFICIO,Remoto,5. >=30,No,3,0

In [10]:
# Data Inspection
# Check the first few rows
#print(data.head())

# Get data types and missing values
print(data.info())

# Summary statistics of numerical columns
#print(data.describe())

# Check for missing values
print(data.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37582 entries, 0 to 37581
Data columns (total 21 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   ENROLLMENT                       37582 non-null  object
 1   TUITION PAYMENT MARCH 2022       37582 non-null  int64
 2   TUITION PAYMENT MARCH 2023       37582 non-null  int64
 3   GENDER                           37580 non-null  object
 4   TYPE OF EDUCATIONAL INSTITUTION  15868 non-null  object
 5   EDUCATIONAL INSTITUTION          18212 non-null  object
 6   INSTITUTION STATUS               15868 non-null  object
 7   DEPARTMENT                       36846 non-null  object
 8   PROVINCE                         36846 non-null  object
 9   DISTRICT                         36846 non-null  object
 10  CLASSIFICATION                   37581 non-null  object
 11  CAMPUS                           37582 non-null  object
 12  FACULTY                          37581 non-null  object
 13  PROGRAM/MAJOR                    37581 non-null  object
 14  SHIFT/SCHEDULE                   37524 non-null  object
 15  BENEFIT DISCOUNTS                37582 non-null  object
 16  STUDY MODE                       37582 non-null  object
 17  AGE RANGE OF ENROLLED STUDENT    37578 non-null  object
 18  DISABILITY                       37582 non-null  object
 19  NUMBER OF ENROLLED COURSES       37582 non-null  int64
 20  AT-RISK COURSE                   37582 non-null  int64
dtypes: int64(4), object(17)
memory usage: 6.0+ MB
None
ENROLLMENT                             0
TUITION PAYMENT MARCH 2022             0
TUITION PAYMENT MARCH 2023             0
GENDER                                 2
TYPE OF EDUCATIONAL INSTITUTION    21714
EDUCATIONAL INSTITUTION            19370
INSTITUTION STATUS                 21714
DEPARTMENT                           736
PROVINCE                             736
DISTRICT                             736
CLASSIFICATION                         1
CAMPUS                                 0
FACULTY                                1
PROGRAM/MAJOR                          1
SHIFT/SCHEDULE                        58
BENEFIT DISCOUNTS                      0
STUDY MODE                             0
AGE RANGE OF ENROLLED STUDENT          4
DISABILITY                             0
NUMBER OF ENROLLED COURSES             0
AT-RISK COURSE                         0
dtype: int64